"""
Reminder Agent.

Formats the final `prioritized_list` into a clean Markdown message and
pushes it to a Telegram channel/chat via the Bot API's sendMessage
endpoint. This is the terminal node in the pipeline.
"""

from typing import Dict, Any, List

import requests

from src.graph.state import AgentState
from src.config import TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID

_TRACK_EMOJIS = {
    "IITB Coursework": "🏫",
    "SoS Project": "🔬",
    "LeetCode": "💻",
}

_TELEGRAM_API_URL_TEMPLATE = "https://api.telegram.org/bot{token}/sendMessage"


def _format_message(prioritized_list: List[Dict[str, Any]]) -> str:
    """Build a clean, emoji-annotated Markdown message body."""
    if not prioritized_list:
        return "📋 *IITB Weekly Assistant*\n\nNo tasks found for this period\\. Enjoy the free time\\!"

    lines = ["📋 *IITB Weekly Deadline Digest*", ""]

    for idx, task in enumerate(prioritized_list, start=1):
        track = task.get("track", "Unknown")
        emoji = _TRACK_EMOJIS.get(track, "📌")
        title = str(task.get("title", "Untitled task")).strip()
        deadline = task.get("original_deadline", "Unspecified")
        score = task.get("priority_score", 0)

        lines.append(f"{idx}\\. {emoji} *{title}*")
        lines.append(f"   ├ Track: _{track}_")
        lines.append(f"   ├ Deadline: `{deadline}`")
        lines.append(f"   └ Priority Score: `{score}`")
        lines.append("")

    lines.append("_Generated by the IITB Study/Deadline Assistant_")
    return "\n".join(lines)


def _escape_markdown_v2(text: str) -> str:
    """Escape MarkdownV2 reserved characters that appear outside our own formatting tokens."""
    # Note: since we hand-construct the message with intentional MarkdownV2
    # tokens (*, _, `, \.), we do not blanket-escape here to avoid corrupting
    # our own formatting. This helper is kept for any raw user-supplied text
    # that might need sanitizing in future extensions.
    reserved = r"_*[]()~`>#+-=|{}.!"
    return "".join(f"\\{ch}" if ch in reserved else ch for ch in text)


def run_reminder_agent(state: AgentState) -> Dict[str, Any]:
    """
    Send the prioritized schedule to Telegram.

    Args:
        state: Current graph state containing `prioritized_list`.

    Returns:
        A partial state update dict containing `telegram_status`
        ("SUCCESS" or "FAILED").
    """
    prioritized_list = state.get("prioritized_list", [])
    message_text = _format_message(prioritized_list)

    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        print(
            "[REMINDER ERROR] TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID is not configured. "
            "Skipping delivery."
        )
        print("---- Message that would have been sent ----")
        print(message_text)
        print("--------------------------------------------")
        return {"telegram_status": "FAILED"}

    url = _TELEGRAM_API_URL_TEMPLATE.format(token=TELEGRAM_BOT_TOKEN)
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message_text,
        "parse_mode": "MarkdownV2",
        "disable_web_page_preview": True,
    }

    try:
        response = requests.post(url, json=payload, timeout=10)

        if response.status_code == 200 and response.json().get("ok"):
            print("[REMINDER] Schedule successfully delivered to Telegram.")
            return {"telegram_status": "SUCCESS"}

        print(
            f"[REMINDER ERROR] Telegram API returned status "
            f"{response.status_code}: {response.text}"
        )
        return {"telegram_status": "FAILED"}

    except requests.exceptions.RequestException as exc:
        print(f"[REMINDER ERROR] Network/request failure while contacting Telegram: {exc}")
        return {"telegram_status": "FAILED"}
    except Exception as exc:  # noqa: BLE001
        print(f"[REMINDER ERROR] Unexpected failure during delivery: {exc}")
        return {"telegram_status": "FAILED"}